name: bankapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  device_frame_plus: ^1.5.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/MyCustomFont-Bold.ttf
          weight: 700
        - asset: assets/fonts/MyCustomFont-Regular.ttf
          weight: 400
        - asset: assets/fonts/MyCustomFont-Medium.ttf
          weight: 500
        - asset: assets/fonts/MyCustomFont-Italic.ttf
          style: italic
